package entities

import "github.com/lib/pq"

type Meta struct {
	ID                            string         `xorm:"id"`
	Name                          string         `xorm:"name"`
	Description                   string         `xorm:"description"`
	MaintainerName                string         `xorm:"maintainerName"`
	MaintainerEmail               string         `xorm:"maintainerEmail"`
	DisableRegistration           bool           `xorm:"disableRegistration"`
	DisableLocalTimeline          bool           `xorm:"disableLocalTimeline"`
	DisableGlobalTimeline         bool           `xorm:"disableGlobalTimeline"`
	UseStarForReactionFallback    bool           `xorm:"useStarForReactionFallback"`
	PinnedUsers                   pq.StringArray `xorm:"pinnedUsers"`
	HiddenTags                    pq.StringArray `xorm:"hiddenTags"`
	BlockedHosts                  pq.StringArray `xorm:"blockedHosts"`
	BlockedEmailDomains           pq.StringArray `xorm:"blockedEmailDomains"`
	PinnedClipID                  string         `xorm:"pinnedClipId"`
	ThemeColor                    string         `xorm:"themeColor"`
	MascotImageURL                string         `xorm:"mascotImageUrl"`
	BannerURL                     string         `xorm:"bannerUrl"`
	BackgroundImageURL            string         `xorm:"backgroundImageUrl"`
	LogoImageUrl                  string         `xorm:"logoImageUrl"`
	ErrorImageUrl                 string         `xorm:"errorImageUrl"`
	IconUrl                       string         `xorm:"iconUrl"`
	CacheRemoteFiles              bool           `xorm:"cacheRemoteFiles"`
	ProxyAccountID                string         `xorm:"proxyAccountId"`
	EmailRequiredForSignup        bool           `xorm:"emailRequiredForSignup"`
	EnableHcaptcha                bool           `xorm:"enableHcaptcha"`
	HcaptchaSiteKey               string         `xorm:"hcaptchaSiteKey"`
	HcaptchaSecretKey             string         `xorm:"hcaptchaSecretKey"`
	EnableRecaptcha               bool           `xorm:"enableRecaptcha"`
	RecaptchaSiteKey              string         `xorm:"recaptchaSiteKey"`
	RecaptchaSecretKey            string         `xorm:"recaptchaSecretKey"`
	EnableTurnstile               bool           `xorm:"enableTurnstile"`
	TurnstileSiteKey              string         `xorm:"turnstileSiteKey"`
	TurnstileSecretKey            string         `xorm:"turnstileSecretKey"`
	LocalDriveCapacityMB          int            `xorm:"localDriveCapacityMb"`
	RemoteDriveCapacityMB         int            `xorm:"remoteDriveCapacityMb"`
	SummalyProxy                  string         `xorm:"summalyProxy"`
	EnableEmail                   bool           `xorm:"enableEmail"`
	Email                         string         `xorm:"email"`
	SMTPSecure                    bool           `xorm:"smtpSecure"`
	SMTPHost                      string         `xorm:"smtpHost"`
	SMTPPort                      int            `xorm:"smtpPort"`
	SMTPUser                      string         `xorm:"smtpUser"`
	SMTPPass                      string         `xorm:"smtpPass"`
	EnableServiceWorker           bool           `xorm:"enableServiceWorker"`
	SWPublicKey                   string         `xorm:"swPublicKey"`
	SWPrivateKey                  string         `xorm:"swPrivateKey"`
	DeeplAuthKey                  string         `xorm:"deeplAuthKey"`
	DeeplIsPro                    bool           `xorm:"deeplIsPro"`
	ToSURL                        string         `xorm:"ToSUrl"`
	RepositoryURL                 string         `xorm:"repositoryUrl"`
	FeedbackURL                   string         `xorm:"feedbackUrl"`
	DefaultLightTheme             string         `xorm:"defaultLightTheme"`
	DefaultDarkTheme              string         `xorm:"defaultDarkTheme"`
	UseObjectStorage              bool           `xorm:"useObjectStorage"`
	ObjectStorageBucket           string         `xorm:"objectStorageBucket"`
	ObjectStoragePrefix           string         `xorm:"objectStoragePrefix"`
	ObjectStorageBaseURL          string         `xorm:"objectStorageBaseUrl"`
	ObjectStorageEndpoint         string         `xorm:"objectStorageEndpoint"`
	ObjectStorageRegion           string         `xorm:"objectStorageRegion"`
	ObjectStorageAccessKey        string         `xorm:"objectStorageAccessKey"`
	ObjectStorageSecretKey        string         `xorm:"objectStorageSecretKey"`
	ObjectStoragePort             int            `xorm:"objectStoragePort"`
	ObjectStorageUseSSL           bool           `xorm:"objectStorageUseSSL"`
	ObjectStorageUseProxy         bool           `xorm:"objectStorageUseProxy"`
	ObjectStorageSetPublicRead    bool           `xorm:"objectStorageSetPublicRead"`
	ObjectStorageS3ForcePathStyle bool           `xorm:"objectStorageS3ForcePathStyle"`
	EnableIpLogging               bool           `xorm:"enableIpLogging"`
	EnableActiveEmailValidation   bool           `xorm:"enableActiveEmailValidation"`
}
