name: Unit Test (Go)

on:
  pull_request:
    types:
        - opened
        - synchronize
  push:
    branches:
      - "**"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: "1.21.5"

      - name: Run go test for all packages
        run: go test ./...
